pipeline {
    agent any

    stages {
        stage('Build g++') {
            steps {
                echo 'Building devenv ... g++ make '
		        sh 'make image'
            }
	    }
        stage('Build clang') {
            steps {
                echo 'Building devenv ... clang++ make '
		        sh 'make image CXX=clang++'
            }
	    }
    }
}