<div class="side">
     <h2><!--#i18n key="generic.menu.title" --></h2>
  
	 <!-- Navigation Bar -->
     <div class="navbar">

      <ul class="nav">
       <li>
            <a href="/" hx-target="#main" hx-push-url="true" hx-select="#main" hx-swap="outerHTML" hx-get="/"><!--#i18n key="generic.menu.home" --></a>
       </li>
       <li>
            <a href="/login" hx-target="#main" hx-push-url="true" hx-select="#main" hx-swap="outerHTML" hx-get="/login"><!--#i18n key="generic.menu.login" --></a>
       </li>
       <li>
            <a href="/register" hx-target="#main" hx-push-url="true" hx-select="#main" hx-swap="outerHTML" hx-get="/register"><!--#i18n key="generic.menu.register" --></a>
        </li>
        <li>
            <a href="/logout" hx-target="#main" hx-push-url="true" hx-select="#main" hx-swap="outerHTML" hx-get="/logout"><!--#i18n key="generic.menu.logout" --></a>
        </li>
        </ul>
    
    </div>      
</div>
