version: '2'
services:
  web:
    build: 
      context: .
      dockerfile: ${DOCKERFILE}
      args:
        CXX: ${CXX}
        EVENTLIB: ${EVENTLIB}
        BASE_IMAGE: ${BASE_IMAGE}
    ports:
     - "9876:9876"
    