<div class="header">
  <b><!--#i18n key="generic.header.headline" --></b>
  <span><!--#i18n key="generic.header.headline.desc" --></span>
  <a href="https://github.com/littlemole/wpp"><!--#i18n key="generic.header.headline.home" --></a>
  <a href="https://github.com/littlemole/wpp/tree/main/example"><!--#i18n key="generic.header.headline.examples" --></a>
  <a href="https://github.com/littlemole/wpp/tree/main/example/hello_ws_coro"><!--#i18n key="generic.header.headline.this.example" --></a>
</div>